import { Geist, Geist_Mono, Jost, Lato } from "next/font/google";
import "./globals.css";
import { ToastContainer } from "react-toastify";
import ReduxProvider from "@/Providers/ReduxProvider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const googleJost = Jost({
  variable: "--font-Jost",
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

const googleLato = Lato({
  variable: "--font-Lato",
  weight: ["100", "300", "400", "700", "900"],
});

export const metadata = {
  title: "United furniture uae",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${googleJost.variable} ${googleLato.variable} antialiased`}
      >
        <ReduxProvider>
          <ToastContainer />
          {children}
        </ReduxProvider>
      </body>
    </html>
  );
}

// <ReduxProvider>
//         {children}
//       </ReduxProvider>
