import { Geist, Geist_Mono, Jost, Lato } from "next/font/google";
import "./globals.css";
import { ToastContainer } from "react-toastify";
import ReduxProvider from "@/Providers/ReduxProvider";
import { FaWhatsapp } from "react-icons/fa";
import { QueryClient, QueryClientProvider } from "@tanstack/react-query";

const geistSans = Geist({ variable: "--font-geist-sans", subsets: ["latin"] });
const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});
const googleJost = Jost({
  variable: "--font-Jost",
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});
const googleLato = Lato({
  variable: "--font-Lato",
  weight: ["100", "300", "400", "700", "900"],
});

export const metadata = {
  title: "United furniture uae",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${googleJost.variable} ${googleLato.variable} antialiased`}
      >
        <ReduxProvider>
          <ToastContainer />
          {children}
          <a
            href="https://wa.me/+8801611239608"
            target="_blank"
            rel="noopener noreferrer"
            style={{
              position: "fixed",
              bottom: "20px",
              right: "20px",
              backgroundColor: "#25D366",
              color: "#fff",
              borderRadius: "50%",
              width: "60px",
              height: "60px",
              display: "flex",
              justifyContent: "center",
              alignItems: "center",
              fontSize: "28px",
              zIndex: 1000,
              boxShadow: "0 4px 12px rgba(0,0,0,0.3)",
              transition: "transform 0.2s",
            }}
          >
            <FaWhatsapp />
          </a>
        </ReduxProvider>
      </body>
    </html>
  );
}
